version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # Use the appropriate image for your project
    steps:
      - checkout

      # Install SonarScanner
      - run:
          name: Install SonarScanner
          command: |
            wget https://dl.bintray.com/sonarsource/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            unzip sonar-scanner-cli-4.7.0.2747-linux.zip -d /opt/

      # Run SonarCloud Analysis
      - run:
          name: Run SonarCloud Analysis
          command: |
            /opt/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.sources=./src  # Adjust this path to where your source code is
