version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install pytest

      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test-results/results.xml

      - run:
          name: Install SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            mv sonar-scanner-5.0.1.3006-linux sonar-scanner
            export PATH=$PATH:$(pwd)/sonar-scanner/bin
            sonar-scanner -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
