version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # Docker image for Python environment
    steps:
      - checkout  # Get the code
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt  # Install project dependencies
      - run:
          name: Run Tests
          command: |
            python -m unittest discover -s tests  # Run the unit tests
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-docker-username/your-image-name:latest .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push your-docker-username/your-image-name:latest  # Push image to Docker Hub

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
